drop database IF EXISTS st2eedb;
CREATE DATABASE st2eedb ENCODING DEFAULT CONNECTION LIMIT -1;

GRANT ALL PRIVILEGES ON DATABASE st2eedb TO adm;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to adm;

CREATE TABLE supervisor (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    mail VARCHAR(100) NOT NULL
);